### ISSUE TITLE
Add support for local file system repos (in the `docker-compose`/local experience)

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#635]
Add support for local filesystem Git repos in the `docker-compose` MergeStat experience so that local users can point MergeStat at repositories they already have on disk.

We will likely need to produce some instructions on how to mount a host volume on the `worker` service.

**Comment by riyaz-ali** [comment]
This can be achieved by creating an override `docker-compose.yaml` file locally (by the end user) and adding a bind-mount volume.

```yaml
services:
  worker:
    volumes:
      - ~/projects:/projects # this can be any local path
```
Then, from the UI, the repository can be added by using a `file://` url:

![image](https://user-images.githubusercontent.com/17478576/207533264-c17a2319-5ae3-42c3-bb48-157e96b733ea.png)
